default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my_project_development

test:
  <<: *default
  database: my_project_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
# ЦЕ КОМЕНТАР ДЛЯ ТЕСТУ ДЕПЛОЮ

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>