default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: try_app_db

test:
  <<: *default
  database: try_app_db

production:
  <<: *default
  database: try_app_db

queue:
  <<: *production
  database: try_app_db

# ✅ Додай ось це
cable:
  <<: *default
  database: try_app_db
