  default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5 # Кількість з'єднань
    
    development:
      <<: *default
      database: my_app_development # Ви можете назвати її як завгодно
      # --- Вам може знадобитися додати це, якщо Postgres запитує пароль ---
      # username: postgres
      # password: ваш_пароль
      # host: localhost
    
    test:
      <<: *default
      database: my_app_test
    
    production:
      <<: *default
      # Цей рядок каже Rails брати налаштування БД
      # зі змінної середовища DATABASE_URL, яку нам дасть Render.
      url: <%= ENV["DATABASE_URL"] %>